# Generated by Django 4.0 on 2024-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avarar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avarar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
